import type IconData from "../types/IconData.ts";
import {
  flutterLogo,
  openglLogo,
  reactLogo,
  vueLogo,
} from "@static/pathTechFrameworkItems.ts";
import {
  assemblyLogo,
  cPlusLogo,
  cSharpLogo,
  cssLogo,
  dartLogo,
  htmlLogo,
  javaLogo,
  jsLogo,
  kotlinLogo,
  phpLogo,
  swiftLogo,
} from "@static/pathTechLanguageItems.ts";
import {
  androidLogo,
  firebaseLogo,
  iosLogo,
} from "@static/pathTechSoftwareItems.ts";
import {
  aeLogo,
  blenderLogo,
  dsmax,
  prLogo,
  unityLogo,
} from "@static/pathTechIDEItems.ts";

export interface IconProjectData extends IconData {
  title: string;
  subtitle: string;
  pathTech: IconData[];
  github?: string;
  demo: boolean;
}

const projectItems: IconProjectData[] = [
  {
    src: "/images/projects/project_plogging-challenge.png",
    alt: "Plogging Challenge app",
    title: "Plogging Challenge - App en Flutter para Android e IOS!",
    subtitle: "App Android e IOS",
    pathTech: [flutterLogo, dartLogo, firebaseLogo, androidLogo, iosLogo],
    github: "https://github.com/jma83/TFM_flutter_plogging_app",
    demo: false,
  },
  {
    src: "/images/projects/project_rick-and-morty.png",
    alt: "Rick and Morty hybrid app",
    title: "Rickpedia - App en ReactNative para Android e IOS!",
    subtitle: "App Android e IOS",
    pathTech: [reactLogo, cssLogo, androidLogo, iosLogo],
    github: "https://github.com/jma83/ReactNativeProject",
    demo: false,
  },
  {
    src: "/images/projects/project_fit-up.png",
    alt: "Fit Up Android app",
    title: "FitUp - App de entrenamientos para Android!",
    subtitle: "App Android",
    pathTech: [javaLogo, kotlinLogo, androidLogo],
    github: "https://github.com/jma83/PracticaAndroid-FitUp",
    demo: false,
  },
  {
    src: "/images/projects/project_books.png",
    alt: "Books IOS app",
    title: "Books - App en Swift para IOS!",
    subtitle: "App IOS",
    pathTech: [iosLogo, swiftLogo],
    github: "https://github.com/jma83/PracticaIOS",
    demo: false,
  },
  {
    src: "/images/projects/project_movie-guessr.png",
    alt: "Movie Guessr game",
    title: "MovieGuessr - Juego para web en JS!",
    subtitle: "Página web",
    pathTech: [vueLogo, htmlLogo, cssLogo, jsLogo],
    github: "https://github.com/jma83/WordGuesser",
    demo: true,
  },
  {
    src: "/images/projects/project_volley-force.png",
    alt: "Volley Force game",
    title: "VolleyForce - Juego en 1 semana en Unity",
    subtitle: "Videojuego",
    pathTech: [unityLogo, cSharpLogo],
    github: "https://github.com/jma83/VolleyBall_Project",
    demo: true,
  },
  {
    src: "/images/projects/project_hunger.png",
    alt: "Hunger web game",
    title: "Ahorcado - Juego para web en JS!",
    subtitle: "Página web",
    pathTech: [reactLogo, cssLogo],
    github: "https://github.com/jma83/AhorcadoWebReact",
    demo: true,
  },
  {
    src: "/images/projects/project_three-in-line.png",
    alt: "Three in line web game",
    title: "3 en raya - Juego para web en JS!",
    subtitle: "Página web",
    pathTech: [htmlLogo, cssLogo, jsLogo],
    github: "https://github.com/jma83/TresEnLinea",
    demo: true,
  },
  {
    src: "/images/projects/project_age-of-karts.png",
    alt: "Age of Karts game",
    title: "Age of Karts - Videojuego en C++ y OpenGL",
    subtitle: "Videojuego",
    pathTech: [cPlusLogo, openglLogo],
    github: "https://github.com/tomrock8/Age-of-karts",
    demo: false,
  },
  {
    src: "/images/projects/project_football.png",
    alt: "Football web game",
    title: "Juego de fútbol Web - Utilizando Canvas y Vanilla js",
    subtitle: "Página web",
    pathTech: [htmlLogo, cssLogo, jsLogo],
    demo: true,
  },
  {
    src: "/images/projects/project_ar-hunters.png",
    alt: "AR Hunters game",
    title: "ARHunters - Videojuego de Realidad aumentada para Android",
    subtitle: "Videojuego Android",
    pathTech: [unityLogo, cSharpLogo],
    github: "https://github.com/jma83/TFG_AR",
    demo: false,
  },
  {
    src: "/images/projects/project_lightning-video.png",
    alt: "Lighting video editing",
    title: "Generar Rayos entre dedos - Postproducción digital",
    subtitle: "Edición de video",
    pathTech: [aeLogo, prLogo],
    demo: true,
  },
  {
    src: "/images/projects/project_blender-models.png",
    alt: "Blender 3d models",
    title: "Modelado objetos 3D en Blender",
    subtitle: "Modelado 3D",
    pathTech: [blenderLogo],
    demo: false,
  },
  {
    src: "/images/projects/project_pixar-animation.png",
    alt: "Pixar animation game",
    title: "Animación Pixar Modificada (Modelado y Animación 3D)",
    subtitle: "Modelado y animación 3D",
    pathTech: [dsmax],
    demo: true,
  },
  {
    src: "/images/projects/project_pixel-brawl.png",
    alt: "Pixel brawl game",
    title: "Amstrad CPC: Pixel Brawl (Ensablador)",
    subtitle: "Videojuego",
    pathTech: [assemblyLogo],
    demo: false,
  },
  {
    src: "/images/projects/project_saloon-scene.png",
    alt: "Saloon 3d scene",
    title: "Escena interior de Saloon",
    subtitle: "Modelado 3D",
    pathTech: [dsmax],
    demo: false,
  },
  {
    src: "/images/projects/project_lego-scene.png",
    alt: "Lego 3d scene",
    title: "Escena casa de Lego",
    subtitle: "Modelado 3D",
    pathTech: [dsmax],
    demo: false,
  },
  {
    src: "/images/projects/project_hardware-zone.png",
    alt: "HardwareZone web",
    title: "Hardwarezone - Web de compras online con Wordpress",
    subtitle: "Página web",
    pathTech: [htmlLogo, cssLogo, phpLogo],
    demo: false,
  },
  {
    src: "/images/projects/project_dragon-ware.png",
    alt: "DragonWare web",
    title: "DragonWare - Web de compras online con Wix",
    subtitle: "Página web",
    pathTech: [htmlLogo, cssLogo],
    demo: true,
  },
  {
    src: "/images/projects/project_own-mind.png",
    alt: "OwnMind web",
    title: "OwnMind - Red social con vanilla js",
    subtitle: "Página web",
    pathTech: [htmlLogo, cssLogo, jsLogo],
    demo: true,
  },
  {
    src: "/images/projects/project_picstories.png",
    alt: "PicStories web",
    title: "PicStories - Red social con PHP",
    subtitle: "Página web",
    pathTech: [htmlLogo, cssLogo, phpLogo],
    demo: false,
  },
  {
    src: "/images/projects/project_frozen-hearts.png",
    alt: "Frozen Hearts game",
    title:
      "Frozen Hearts - Videjouego multiplataforma desarrollado en GameMaker",
    subtitle: "Videojuego Android y Windows",
    pathTech: [cPlusLogo],
    demo: false,
  },
  {
    src: "/images/projects/project_olympic.png",
    alt: "Olympic web",
    title: "Olympic - Red social con WordPress",
    subtitle: "Página web",
    pathTech: [htmlLogo, cssLogo, phpLogo],
    demo: false,
  },
  {
    src: "/images/projects/project_fridge.png",
    alt: "Fridge web",
    title: "Nevera web - Comienzos con HTML, CSS y JS",
    subtitle: "Página web",
    pathTech: [htmlLogo, cssLogo, jsLogo],
    demo: false,
  },
];

export default projectItems;
