import type IconData from "@types/IconData.ts";
import {
  flutterLogo,
  openglLogo,
  reactLogo,
  svelteLogo,
  vueLogo,
} from "@static/pathTechFrameworkItems.ts";
import {
  assemblyLogo,
  cPlusLogo,
  cSharpLogo,
  cssLogo,
  dartLogo,
  htmlLogo,
  javaLogo,
  jsLogo,
  kotlinLogo,
  phpLogo,
  swiftLogo,
} from "@static/pathTechLanguageItems.ts";
import {
  androidLogo,
  firebaseLogo,
  iosLogo,
} from "@static/pathTechSoftwareItems.ts";
import {
  aeLogo,
  blenderLogo,
  dsmax,
  prLogo,
  unityLogo,
} from "@static/pathTechIDEItems.ts";

export interface IconProjectData extends IconData {
  title: string;
  subtitle: string;
  description: string;
  pathTech: IconData[];
  github?: string;
  demo: boolean | string;
}

const projectItems: IconProjectData[] = [
  {
    src: "/images/projects/project_fav-films.avif",
    alt: "FavFilms Web",
    title: "projects.favfilms.title",
    subtitle: "projects.favfilms.subtitle",
    description: "projects.favfilms.description",
    pathTech: [reactLogo],
    github: "https://github.com/jma83/react-fav-movies",
    demo: "https://fav-films.vercel.app/",
  },
  {
    src: "/images/projects/project_todo-list-svelte.avif",
    alt: "Todo list App",
    title: "projects.todolist.title",
    subtitle: "projects.todolist.subtitle",
    description: "projects.todolist.description",
    pathTech: [svelteLogo],
    github: "https://github.com/jma83/svelte-todo",
    demo: "https://svelte-todo-rouge.vercel.app/",
  },
  {
    src: "/images/projects/project_plogging-challenge.avif",
    alt: "Plogging Challenge app",
    title: "projects.plogging.title",
    subtitle: "projects.plogging.subtitle",
    description: "projects.plogging.description",
    pathTech: [flutterLogo, dartLogo, firebaseLogo, androidLogo, iosLogo],
    github: "https://github.com/jma83/TFM_flutter_plogging_app",
    demo: false,
  },
  {
    src: "/images/projects/project_rick-and-morty.avif",
    alt: "Rick and Morty hybrid app",
    title: "projects.rickpedia.title",
    subtitle: "projects.rickpedia.subtitle",
    description: "projects.rickpedia.description",
    pathTech: [reactLogo, cssLogo, androidLogo, iosLogo],
    github: "https://github.com/jma83/ReactNativeProject",
    demo: false,
  },
  {
    src: "/images/projects/project_fit-up.avif",
    alt: "Fit Up Android app",
    title: "projects.fitup.title",
    subtitle: "projects.fitup.subtitle",
    description: "projects.fitup.description",
    pathTech: [javaLogo, kotlinLogo, androidLogo],
    github: "https://github.com/jma83/PracticaAndroid-FitUp",
    demo: false,
  },
  {
    src: "/images/projects/project_books.avif",
    alt: "Books IOS app",
    title: "projects.books.title",
    subtitle: "projects.books.subtitle",
    description: "projects.books.description",
    pathTech: [iosLogo, swiftLogo],
    github: "https://github.com/jma83/PracticaIOS",
    demo: false,
  },
  {
    src: "/images/projects/project_movie-guessr.avif",
    alt: "Movie Guessr game",
    title: "projects.moviegussr.title",
    subtitle: "projects.moviegussr.subtitle",
    description: "projects.moviegussr.description",
    pathTech: [vueLogo, htmlLogo, cssLogo, jsLogo],
    github: "https://github.com/jma83/WordGuesser",
    demo: "https://movie-guessr.onrender.com/",
  },
  {
    src: "/images/projects/project_volley-force.avif",
    alt: "Volley Force game",
    title: "projects.volleyforce.title",
    subtitle: "projects.volleyforce.subtitle",
    description: "projects.volleyforce.description",
    pathTech: [unityLogo, cSharpLogo],
    github: "https://github.com/jma83/VolleyBall_Project",
    demo: "https://www.jmartdev.ovh/games/volleyball",
  },
  {
    src: "/images/projects/project_hunger.avif",
    alt: "Hunger web game",
    title: "projects.hunger.title",
    subtitle: "projects.hunger.subtitle",
    description: "projects.hunger.description",
    pathTech: [reactLogo, cssLogo],
    github: "https://github.com/jma83/AhorcadoWebReact",
    demo: "https://www.jmartdev.ovh/games/hunger",
  },
  {
    src: "/images/projects/project_three-in-line.avif",
    alt: "Three in line web game",
    title: "projects.line3.title",
    subtitle: "projects.line3.subtitle",
    description: "projects.line3.description",
    pathTech: [htmlLogo, cssLogo, jsLogo],
    github: "https://github.com/jma83/TresEnLinea",
    demo: "https://www.jmartdev.ovh/games/tictactoe",
  },
  {
    src: "/images/projects/project_age-of-karts.avif",
    alt: "Age of Karts game",
    title: "projects.ageofkarts.title",
    subtitle: "projects.ageofkarts.subtitle",
    description: "projects.ageofkarts.description",
    pathTech: [cPlusLogo, openglLogo],
    github: "https://github.com/tomrock8/Age-of-karts",
    demo: false,
  },
  {
    src: "/images/projects/project_football.avif",
    alt: "Football web game",
    title: "projects.football.title",
    subtitle: "projects.football.subtitle",
    description: "projects.football.description",
    pathTech: [htmlLogo, cssLogo, jsLogo],
    demo: "https://www.jmartdev.ovh/games/football",
  },
  {
    src: "/images/projects/project_ar-hunters.avif",
    alt: "AR Hunters game",
    title: "projects.arhunters.title",
    subtitle: "projects.arhunters.subtitle",
    description: "projects.arhunters.description",
    pathTech: [unityLogo, cSharpLogo],
    github: "https://github.com/jma83/TFG_AR",
    demo: "https://www.youtube.com/watch?v=kTjyDpU0oDU",
  },
  {
    src: "/images/projects/project_lightning-video.avif",
    alt: "Lighting video editing",
    title: "projects.lighting.title",
    subtitle: "projects.lighting.subtitle",
    description: "projects.lighting.description",
    pathTech: [aeLogo, prLogo],
    demo: "https://www.youtube.com/watch?v=IcIqs7DkU_s",
  },
  {
    src: "/images/projects/project_blender-models.avif",
    alt: "Blender 3d models",
    title: "projects.models.title",
    subtitle: "projects.models.subtitle",
    description: "projects.models.description",
    pathTech: [blenderLogo],
    demo: false,
  },
  {
    src: "/images/projects/project_pixar-animation.avif",
    alt: "Pixar animation game",
    title: "projects.pixar.title",
    subtitle: "projects.pixar.subtitle",
    description: "projects.pixar.description",
    pathTech: [dsmax],
    demo: "https://www.youtube.com/watch?v=zq93Zc0yXWY",
  },
  {
    src: "/images/projects/project_pixel-brawl.avif",
    alt: "Pixel brawl game",
    title: "projects.pixel.title",
    subtitle: "projects.pixel.subtitle",
    description: "projects.pixel.description",
    pathTech: [assemblyLogo],
    demo: false,
  },
  {
    src: "/images/projects/project_saloon-scene.avif",
    alt: "Saloon 3d scene",
    title: "projects.saloon.title",
    subtitle: "projects.saloon.subtitle",
    description: "projects.saloon.description",
    pathTech: [dsmax],
    demo: false,
  },
  {
    src: "/images/projects/project_lego-scene.avif",
    alt: "Lego 3d scene",
    title: "projects.lego.title",
    subtitle: "projects.lego.subtitle",
    description: "projects.lego.description",
    pathTech: [dsmax],
    demo: false,
  },
  {
    src: "/images/projects/project_hardware-zone.avif",
    alt: "HardwareZone web",
    title: "projects.hardware.title",
    subtitle: "projects.hardware.subtitle",
    description: "projects.hardware.description",
    pathTech: [htmlLogo, cssLogo, phpLogo],
    demo: false,
  },
  {
    src: "/images/projects/project_dragon-ware.avif",
    alt: "DragonWare web",
    title: "projects.dragonware.title",
    subtitle: "projects.dragonware.subtitle",
    description: "projects.dragonware.description",
    pathTech: [htmlLogo, cssLogo],
    demo: "https://dragonwareshop.wixsite.com/dragonwareinc",
  },
  {
    src: "/images/projects/project_own-mind.avif",
    alt: "OwnMind web",
    title: "projects.ownmind.title",
    subtitle: "projects.ownmind.subtitle",
    description: "projects.ownmind.description",
    pathTech: [htmlLogo, cssLogo, jsLogo],
    demo: false,
  },
  {
    src: "/images/projects/project_picstories.avif",
    alt: "PicStories web",
    title: "projects.picstories.title",
    subtitle: "projects.picstories.subtitle",
    description: "projects.picstories.description",
    pathTech: [htmlLogo, cssLogo, phpLogo],
    demo: false,
  },
  {
    src: "/images/projects/project_frozen-hearts.avif",
    alt: "Frozen Hearts game",
    title: "projects.frozenhearts.title",
    subtitle: "projects.frozenhearts.subtitle",
    description: "projects.frozenhearts.description",
    pathTech: [cPlusLogo],
    demo: "https://drive.google.com/file/d/0B-zG7KrRq1YlaVFnb0xFaTZtc1U/view?resourcekey=0-lvrUry6hANIAercqRPnpKA",
  },
  {
    src: "/images/projects/project_olympic.avif",
    alt: "Olympic web",
    title: "projects.olympic.title",
    subtitle: "projects.olympic.subtitle",
    description: "projects.olympic.description",
    pathTech: [htmlLogo, cssLogo, phpLogo],
    demo: false,
  },
  {
    src: "/images/projects/project_fridge.avif",
    alt: "Fridge web",
    title: "projects.fridge.title",
    subtitle: "projects.fridge.subtitle",
    description: "projects.fridge.description",
    pathTech: [htmlLogo, cssLogo, jsLogo],
    demo: false,
  },
];

export default projectItems;
